services:

  redis:
    container_name: ${REDIS_CONTAINER_HOST}
    image: redis:7.0.15-alpine
    ports:
      - ${REDIS_PORT}:6379
    environment:
      REDIS_USER: ${REDIS_USER}
      REDIS_USER_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DATABASES: ${REDIS_DATABASES}
    volumes:
      - redis_auth_data:/data

  postgres:
    container_name: ${POSTGRES_CONTAINER_HOST}
    image: postgres:16.2-alpine
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGPORT: ${POSTGRES_PORT}
    volumes:
      - pg_auth_data:/var/lib/postgresql/data

  auth_src:
    container_name: auth_service
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/src
    ports:
      - 8001:8001
    environment:
      POSTGRES_HOST: ${POSTGRES_CONTAINER_HOST}
      REDIS_HOST: ${REDIS_CONTAINER_HOST}
    restart: always

volumes:
  redis_auth_data:
    driver: local
  pg_auth_data:
    driver: local