"""empty message

Revision ID: 341cde3d96cf
Revises: a9a0e2fd4b37
Create Date: 2024-07-15 10:13:27.080928

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "341cde3d96cf"
down_revision: Union[str, None] = "a9a0e2fd4b37"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("users", "user")
    op.rename_table("roles", "role")
    op.rename_table("permissions", "permission")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("user", "users")
    op.rename_table("role", "roles")
    op.rename_table("permission", "permissions")
    # ### end Alembic commands ###
